"""
Django settings for tiktok_pm_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path # 确保顶部导入了 Path，如果您使用的是 Django 3.1+
from dotenv import load_dotenv # <-- 导入 load_dotenv

# ====== PyMySQL 兼容层 ======
import pymysql
pymysql.install_as_MySQLdb() # <--- 关键！让 Django 认为它正在使用 mysqlclient
# ===========================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 查找并加载项目根目录下的 .env 文件
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^#h*@eehfevm+vcgoxuae460c!i5&or@sn@7!glhmip#hv(bbn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方框架
    'rest_framework',  # DRF (用于API)
    # 富文本编辑器
    'tinymce',         # 富文本编辑器
    # 您的应用
    'products',  # 注册您的产品应用
    # API 过滤
    'django_filters',  # API过滤
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tiktok_pm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tiktok_pm_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
    #'default': {
    #    'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
    #    'NAME': 'tiktok_products',          # 您的数据库名称 (需提前创建)
    #    'USER': 'root',            # 您的MySQL用户名
    #    'PASSWORD': 'abcd1234',    # 您的MySQL密码
    #    'HOST': '192.168.3.17',                  # 数据库地址
    #    'PORT': '3306',                       # 数据库端口
    #    'OPTIONS': {
    #        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    #        'charset': 'utf8mb4',             # 确保支持emoji和复杂字符
    #    }
    #}
    'default': {
        # 关键修改：将 'django.db.backends.mysql' 替换为 PyMySQL 的引擎路径
        'ENGINE': 'django.db.backends.mysql',  # <-- 必须修改！

        # 修复方式：
        # 1. 在 settings.py 顶部添加一行：
        # import pymysql
        # pymysql.install_as_MySQLdb()
        #
        # 2. 或者直接修改 ENGINE 路径 (更清晰)
        # 'ENGINE': 'pymysql.backends.mysql', # <-- 如果 PyMySQL 提供了此路径 (依赖版本)

        # 鉴于您之前使用 mysqlclient，最简单的方式是使用 PyMySQL 提供的兼容层：
        'NAME': os.environ.get('MYSQL_DB_NAME'),
        'USER': os.environ.get('MYSQL_USER'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD'),
        'HOST': os.environ.get('MYSQL_HOST'),
        'PORT': os.environ.get('MYSQL_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}

# 从环境变量读取信任的来源列表
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'default-fail' # 默认值，至少包含本地
).split(',')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置 DRF 使用 DjangoFilter
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

# =========================================================
# 静态文件配置
# =========================================================

# 1. STATIC_URL (用于浏览器访问，例如：/static/admin/css/...)
# 这个设置在开发和生产环境中都需要
STATIC_URL = 'static/'

# 2. STATIC_ROOT (用于 collectstatic 命令)
# 告诉 Django 将所有静态文件收集到项目根目录下的 'staticfiles' 文件夹中。
# 注意：这是 collectstatic 收集文件的目的地，不要与 STATICFILES_DIRS 混淆。
# 必须使用绝对路径：
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# 如果使用的是 Path：
# STATIC_ROOT = Path(BASE_DIR) / 'staticfiles'