# Generated by Django 5.2.8 on 2025-11-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='TikTok Source ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_1', models.TextField(blank=True, null=True)),
                ('description_2', models.TextField(blank=True, null=True)),
                ('desc_detail', models.TextField(blank=True, null=True)),
                ('desc_detail_1', models.TextField(blank=True, null=True)),
                ('desc_detail_2', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(blank=True, null=True)),
                ('In_stock', models.BooleanField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=16, null=True)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('initial_price_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('initial_price_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sold', models.IntegerField(blank=True, db_index=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('colors', models.JSONField(blank=True, null=True)),
                ('sizes', models.JSONField(blank=True, null=True)),
                ('shipping_fee', models.JSONField(blank=True, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('videos', models.JSONField(blank=True, null=True)),
                ('related_videos', models.JSONField(blank=True, null=True)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('category_url', models.TextField(blank=True, null=True)),
                ('seller_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prodct_rating', models.JSONField(blank=True, null=True)),
                ('promotion_items', models.JSONField(blank=True, null=True)),
                ('shop_performance_metrics', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('input', models.JSONField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TikTok Product',
                'verbose_name_plural': 'TikTok Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.TextField(blank=True, null=True)),
                ('original_url', models.TextField(blank=True, null=True)),
                ('zipline_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name_plural': '产品图片',
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('sku_sales_props', models.JSONField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('purchase_limit', models.IntegerField(blank=True, null=True)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=16, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_original_url', models.TextField(blank=True, null=True)),
                ('image_zipline_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name_plural': '产品变体',
                'db_table': 'product_variations',
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.TextField(blank=True, null=True)),
                ('original_url', models.TextField(blank=True, null=True)),
                ('zipline_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_list', to='products.product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name_plural': '产品视频',
                'db_table': 'product_videos',
            },
        ),
    ]
