# Generated by Django 5.2.8 on 2025-11-21 03:18

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_created_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
    ]
