# Generated by Django 5.2.8 on 2025-11-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_created_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'TikTok Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name_plural': 'TikTok Product Variations'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'verbose_name_plural': 'TikTok Product Videos'},
        ),
    ]
