# Generated by Django 5.2.8 on 2025-11-21 05:41

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='评价人昵称')),
                ('rating', models.SmallIntegerField(blank=True, null=True, verbose_name='评分 (1-5)')),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='评价发生日期')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='原始图片JSON')),
                ('zipline_images', models.JSONField(blank=True, null=True, verbose_name='加速图片JSON')),
                ('created_at', models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'TikTok Product Review',
                'verbose_name_plural': 'TikTok Product Reviews',
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
