# Generated by Django 5.2.8 on 2025-12-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_store_remove_product_store_name_product_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodct_rating',
            new_name='product_rating',
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
