# Generated by Django 5.2.8 on 2025-12-18 01:33

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_prodct_rating_product_product_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="存入数据库的唯一标识，如 'candidate'", unique=True)),
                ('name', models.CharField(help_text="显示给用户的名称，如 '待发布'", max_length=100)),
                ('color', models.CharField(default='#666666', help_text='十六进制颜色，如 #FF5733', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True)),
            ],
            options={
                'verbose_name': 'Tag Definition',
                'verbose_name_plural': 'Tag Definitions',
                'db_table': 'product_tags',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
