# Generated by Django 5.2.8 on 2025-12-25 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_producttagdefinition_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_model', models.CharField(db_index=True, max_length=50, verbose_name='生成模型')),
                ('content_type', models.CharField(choices=[('desc', '产品描述优化'), ('script', '视频拍摄脚本'), ('voice', '视频配音文案'), ('img_prompt', '图片生成提示词'), ('vid_prompt', '视频制作提示词')], db_index=True, max_length=20)),
                ('content_zh', models.TextField(blank=True, verbose_name='中文内容')),
                ('content_en', models.TextField(blank=True, verbose_name='英文内容')),
                ('option_index', models.IntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content_items', to='products.product')),
            ],
            options={
                'db_table': 'ai_content_items',
                'ordering': ['-created_at', 'content_type', 'option_index'],
                'indexes': [models.Index(fields=['product', 'ai_model', 'content_type'], name='ai_content__product_9e8b27_idx')],
            },
        ),
    ]
